#!/usr/bin/env python3
"""Build the Workday API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Strategic Sourcing': 'Strat. Sourcing',
    'Adaptive Planning': 'Adaptive Plan.',
    'Prism Analytics': 'Prism',
    'SOAP Web Services': 'SOAP WS',
    'Financial Mgmt': 'Financials',
    'Performance': 'Performance',
    'Compensation': 'Comp.',
    'Absence Mgmt': 'Absence',
}

LINES = [
    {
        "name": 'HCM Core',
        "color": '#F38B00',
        "stations": [
        ('HCM', (270, 200)),
        ('Person', (430, 175)),
        ('Recruiting', (590, 165)),
        ('Talent', (760, 175)),
        ('Performance', (940, 200)),
        ],
    },
    {
        "name": 'Time, Pay & Benefits',
        "color": '#0E9D6E',
        "stations": [
        ('Time Tracking', (270, 320)),
        ('Payroll', (430, 295)),
        ('Compensation', (610, 295)),
        ('Benefits', (790, 295)),
        ('Absence Mgmt', (970, 320)),
        ],
    },
    {
        "name": 'Finance & Sourcing',
        "color": '#1E5BD0',
        "stations": [
        ('Financial Mgmt', (270, 440)),
        ('Strategic Sourcing', (470, 415)),
        ('Adaptive Planning', (700, 415)),
        ('Prism Analytics', (920, 440)),
        ],
    },
    {
        "name": 'Operations & Common',
        "color": '#7B3FE4',
        "stations": [
        ('Common', (290, 560)),
        ('Staffing', (450, 535)),
        ('Extend', (610, 535)),
        ('WQL', (770, 535)),
        ('RaaS', (920, 560)),
        ],
    },
    {
        "name": 'Web Services',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('SOAP Web Services', (640, 700)),
        ('Adaptive WS', (760, 770)),
        ('WQL WS', (520, 770)),
        ],
    },
]

URL_OVERRIDES = {
    'HCM': 'https://apis.apis.io/apis/workday/hcm-api/',
    'Financial Mgmt': 'https://apis.apis.io/apis/workday/financial-management-api/',
    'Recruiting': 'https://apis.apis.io/apis/workday/recruiting-api/',
    'Time Tracking': 'https://apis.apis.io/apis/workday/time-tracking-api/',
    'Benefits': 'https://apis.apis.io/apis/workday/benefits-api/',
    'Absence Mgmt': 'https://apis.apis.io/apis/workday/absence-management-api/',
    'Compensation': 'https://apis.apis.io/apis/workday/compensation-api/',
    'Payroll': 'https://apis.apis.io/apis/workday/payroll-api/',
    'Person': 'https://apis.apis.io/apis/workday/person-api/',
    'Performance': 'https://apis.apis.io/apis/workday/performance-management-api/',
    'Talent': 'https://apis.apis.io/apis/workday/talent-management-api/',
    'Common': 'https://apis.apis.io/apis/workday/common-api/',
    'Staffing': 'https://apis.apis.io/apis/workday/staffing-api/',
    'Strategic Sourcing': 'https://apis.apis.io/apis/workday/strategic-sourcing-api/',
    'SOAP Web Services': 'https://apis.apis.io/apis/workday/soap-web-services-api/',
    'Prism Analytics': 'https://apis.apis.io/apis/workday/prism-analytics-api/',
    'Extend': 'https://apis.apis.io/apis/workday/extend-api/',
    'RaaS': 'https://apis.apis.io/apis/workday/raas-api/',
    'Adaptive Planning': 'https://apis.apis.io/apis/workday/adaptive-planning-api/',
    'Adaptive WS': 'https://apis.apis.io/apis/workday/adaptive-planning-api/',
    'WQL': 'https://apis.apis.io/apis/workday/wql-api/',
    'WQL WS': 'https://apis.apis.io/apis/workday/wql-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Workday API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: workday/openapi · github.com/api-evangelist/workday',
        out_dir=Path(__file__).resolve().parent,
        out_basename='workday-subway-map',
        provider_id='workday',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
